<!DOCTYPE html>
<html>
  <head>
    <title>Adam Forum</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
      body {
        background-color: #15202B;
        color: #FFF;
        font-family: Arial, sans-serif;
        font-size: 16px;
      }

      .container {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
      }

      .header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
      }

      .logo {
        font-size: 24px;
        font-weight: bold;
      }

      .theme-toggle {
        display: flex;
        align-items: center;
        font-size: 20px;
        cursor: pointer;
      }

      .theme-toggle i {
        margin-right: 10px;
      }

      .form {
        background-color: #1C2938;
        border-radius: 10px;
        padding: 20px;
        margin-bottom: 20px;
      }

      .form label {
        display: block;
        margin-bottom: 10px;
      }

      .form input[type="text"], .form textarea {
        width: 100%;
        padding: 10px;
        border-radius: 5px;
        border: none;
        background-color: #2D3B4A;
        color: #FFF;
        font-family: Arial, sans-serif;
        font-size: 16px;
        margin-bottom: 20px;
      }

      .form textarea {
        height: 150px;
        resize: none;
      }

      .form button[type="submit"] {
        background-color: #1DA1F2;
        color: #FFF;
        font-family: Arial, sans-serif;
        font-size: 16px;
        border: none;
        border-radius: 5px;
        padding: 10px 20px;
        cursor: pointer;
      }

      .message-list {
        list-style: none;
        margin: 0;
        padding: 0;
      }

      .message {
        background-color: #1C2938;
        border-radius: 10px;
        padding: 20px;
        margin-bottom: 20px;
      }

      .message p {
        margin: 0;
      }

      .message strong {
        font-weight: bold;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <header class="header">
        <div class="logo">Adam Forum</div>
        <div class="theme-toggle" id="theme-toggle">
          <i class="fas fa-sun"></i> Light mode
        </div>
      </header>
      <form class="form" id="message-form">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
        <label for="topic">Topic:</label>
        <input type="text" id="topic" name="topic" required>
        <label for="message">Message:</label>
        <textarea id="message" name="message" rows="5" required></textarea>
        <button type="submit">Post</button>
      </form>
      <ul class="message-list" id="message-list"></ul>
    </div>
    <script
